### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ihadabs** [dart-code-checker/dart-code-metrics-action#161]
Thanks for this great package 🤍.

Any plans on updating flutter to 3.7.0 / dart 2.19.0?  

Or maybe using the version from a prev step?
```yaml
            - name: 'Install Flutter'
              uses: subosito/flutter-action@v2
              with:
                  cache: true
                  channel: 'stable'
                  flutter-version: ${{ env.flutter_version }}
```

![CleanShot 2023-02-02 at 20 08 26](https://user-images.githubusercontent.com/34512743/216393821-cb9a465e-7f1c-4fc7-8618-c4d4f694ab9d.png)
