### ISSUE TITLE
[BUG] Action is failing when getting package dependencies

### ISSUE THREAD

**Issue by GroovinChip** [dart-code-checker/dart-code-metrics-action#163]
See [here](https://github.com/GroovinChip/macos_ui/actions/runs/4094492117/jobs/7060737018#step:4:16) for error

* **Dart Code Metrics GitHub Action version:**

**Please show your full configuration:**

<details>

<summary>Configuration</summary>

```yaml
name: Dart Code Metrics
on: [pull_request, workflow_dispatch]

jobs:
  dart-code-metrics:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Dart Code Metrics
        uses: dart-code-checker/dart-code-metrics-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pull_request_comment: true
          fatal_warnings: true
          fatal_performance: true
          fatal_style: true
```

And my `pubspec.yaml`:

```yaml
name: macos_ui
description: Flutter widgets and themes implementing the current macOS design language.
version: 1.10.0
homepage: "https://macosui.dev"
repository: "https://github.com/GroovinChip/macos_ui"

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_code_metrics: ^5.5.1
  flutter_lints: ^2.0.1
  mocktail: ^0.3.0

flutter:
  plugin:
    platforms:
      macos:
        package: dev.groovinchip.macos_ui
        pluginClass: MacOSUiPlugin
```

</details>

**What did you do? Please include the source code example causing the issue.**

Has nothing to do with my code, it's a problem with getting package dependencies

**What did you expect to happen?**
The action to work as it normally does

**What actually happened?**
It failed to run

**Are you willing to submit a pull request to fix this bug?**
N/A
