### ISSUE TITLE
Ssh keys are ignored

### ISSUE THREAD

**Issue by jangruenwaldt** [dart-code-checker/dart-code-metrics-action#58]
I setup an ssh key, but it is ignored when running pub get. I use other github repo dependencies. Can not use this action, because pub get fails / gets stuck in retry loop.

**Comment by dkrutskikh** [comment]
@jangruenwaldt try to setup `github_pat` (GitHub Personal Access Token)

**Comment by jangruenwaldt** [comment]
I tried github_pat, still doesn't work, because ssh:// format is used in pubspec

I guess the main problem here is incompatability to ssh:// in pubspec - if I used another notation probably it works with PAT
But adding ssh keys should still work

**Comment by dkrutskikh** [comment]
@jangruenwaldt why you not use provide dependency in this format:

```
dependencies:
  kittens:
    git:
      url: git@github.com:munificent/kittens.git
      ref: some-branch
```

https://dart.dev/tools/pub/dependencies#git-packages

?
