### ISSUE TITLE
How to configure the Dart SDK version?

### ISSUE THREAD

**Issue by pakona** [dart-code-checker/dart-code-metrics-action#87]
Hello,

I'm trying to create a workflow for dart code metrics in a private repository, but I'm
running into this error message:

```
...
...
Error: The current Dart SDK version is 2.16.1.
  
Because XXX requires SDK version 2.14.4, version solving failed.
...
...
```

Here is the action config:
```
name: Dart Code Metrics
on: [push]
env:
  FLUTTER_SDK_VERSION: 2.5.3

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2.3.0
        with:
          flutter-version: ${{env.FLUTTER_SDK_VERSION}}
          cache: true
      - name: dart-code-metrics
        uses: dart-code-checker/dart-code-metrics-action@v1
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          relative_path: app
          check_unused_files: true
          pull_request_comment: true
```

The application strictly requires Dart 2.14.4.
Any workaround this?
Is there a way to choose which Dart version dart-code-metrics-action will use?
